import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Next.js Blog With Multi Zones (Zone A)</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"flex flex-col items-center"}>
                <h1>
                    Welcome to Multi Zones
                </h1>

                <Link className={"text-red-500"} href="/blog">
                    <h2>Go to Blog (zone B) &rarr;</h2>
                </Link>

                <Link className={"text-blue-500"} href="/about" passHref>
                    <h2>About us (zone A) &rarr;</h2>
                </Link>

                <Link className={"text-red-500"} href="/blog/posts/hello">
                    <h2>Go to Hello post (zone B) &rarr;</h2>
                </Link>
            </main>
        </div>
    )

}
