import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Next.js Blog With Multi Zones (Zone B)</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"flex flex-col items-center"}>
                <h1>
                    Welcome to Zone B
                </h1>

                <Link className={"text-red-500"} href="http://localhost:4444">
                    <h2>Go back to Zone A &rarr;</h2>
                </Link>

                <Link className={"text-blue-500"} href="/posts/hello" passHref>
                    <h2>Go to Hello post &rarr;</h2>
                </Link>
            </main>
        </div>
    );
}
